// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu--F1C488tg_popl4KP7_0mwMk9zBFGw',
    appId: '1:436392614356:android:52f3d138ccbd23a4a59e41',
    messagingSenderId: '436392614356',
    projectId: 'sharing-penalty-14cb9',
    storageBucket: 'sharing-penalty-14cb9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbPICrlGa9Wv08DbnMgJSf4pnyDTuSoos',
    appId: '1:436392614356:ios:458339020d0a391da59e41',
    messagingSenderId: '436392614356',
    projectId: 'sharing-penalty-14cb9',
    storageBucket: 'sharing-penalty-14cb9.appspot.com',
    iosClientId: '436392614356-dk6nidk2picqr4cnm6od27rurjceic0p.apps.googleusercontent.com',
    iosBundleId: 'com.pinoko.sharingPenalty',
  );
}
